// Generated by CoffeeScript 1.4.0
(function() {
  var Alarm, Socket, assert;

  assert = require('chai').assert;

  Alarm = require('../ad2usb');

  Socket = require('./socket');

  describe('Callback', function() {
    var alarm, socket;
    alarm = null;
    socket = null;
    beforeEach(function() {
      socket = new Socket();
      return alarm = new Alarm(socket);
    });
    return it('should callback on sent response', function(done) {
      socket.response = '!Sending..done';
      return alarm.send('12341', function() {
        return done();
      });
    });
  });

}).call(this);
