// Generated by CoffeeScript 1.4.0
(function() {
  var EventEmitter, Socket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  Socket = (function(_super) {

    __extends(Socket, _super);

    function Socket() {
      this.response = null;
    }

    Socket.prototype.write = function(data) {
      this.data = data;
      if (this.response) {
        return this.emit('data', "" + this.response + "\n");
      }
    };

    return Socket;

  })(EventEmitter);

  module.exports = Socket;

}).call(this);
